export const LABELS = {
  en: {
    language: "Language",
    seed: "Seed",
    likes: "Likes",
    reviews: "Reviews",
    title: "Title",
    author: "Author(s)",
    publisher: "Publisher",
    byAuthor: "by",
    review: "Review",
    reviewsCount: "Reviews",
    loading: "Loading...",
    csv: "CSV",
  },
  ru: {
    language: "Язык",
    seed: "Затравка",
    likes: "Лайки",
    reviews: "Отзывы",
    title: "Название",
    author: "Автор(ы)",
    publisher: "Издатель",
    byAuthor: "от",
    review: "Отзыв",
    reviewsCount: "Отзывы",
    loading: "Загрузка...",
    csv: "CSV",
  },
  tr: {
    language: "Dil",
    seed: "Tohum",
    likes: "Beğeni",
    reviews: "Yorumlar",
    title: "Başlık",
    author: "Yazar(lar)",
    publisher: "Yayıncı",
    byAuthor: "tarafından",
    review: "Yorum",
    reviewsCount: "Yorumlar",
    loading: "Yükleniyor...",
    csv: "CSV",
  },
  zh: {
    language: "语言",
    seed: "种子",
    likes: "点赞",
    reviews: "评论",
    title: "书名",
    author: "作者",
    publisher: "出版社",
    byAuthor: "由",
    review: "评论",
    reviewsCount: "评论",
    loading: "加载中...",
    csv: "CSV",
  },
};